apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
spec:
  selector:
    matchLabels:
      app: mysqld-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
      labels:
        app: mysqld-exporter
    spec:
      containers:      
      - name: mysqld-server
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      - name: mysqld-exporter
        image: prom/mysqld-exporter
        env:
        - name: DATA_SOURCE_NAME
          value: root:password@localhost:3306)/
        ports:
        - containerPort: 9104

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
  
      
      
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
  - port: 3306
  -
  selector:
    app: mysqld-exporter
  clusterIP: None



kind: Service
apiVersion: v1
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysqld-exporter
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  - name: mysqld-exporter
    protocol: TCP
    port: 9104
    targetPort: 9104